preprocessing:
  winsorising_threshold: 1.5
  p_value_threshold: 0.05
  minimum_length: 20
  differencing_order: 1

splitting:
  n_splits: 3

model:
  name: sarimax
  params:
    order: [1, 1, 1]
    seasonal_order: [1, 1, 1, 12]
